# -*- coding: utf-8 -*-
"""YOLO_Object_Detection_recordedVideo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F_BbhEwzpZ22QXAo2_Vc_CywLr4j6tw4
"""

!pip install ultralytics -q

from ultralytics import YOLO

!wget -O yolo8n.pt https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt

!yolo detect predict model=yolo8n.pt source= "/cars.mp4"